#!/usr/bin/bash

while true
do
    if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root"
    exit
    fi

    git pull
    chmod ugo=rwx tmp
    chown nobody:nogroup tmp
    sleep 24h
done